### ISSUE TITLE
Adding whole-genome comparisons

### ISSUE THREAD

**Issue by flodebarre** [jbloomlab/CoV_identities#1]
(Suggestion, not issue!)
Would it please be possible to add whole-genome comparisons, on top of comparisons for each gene? Thanks!

**Comment by jbloom** [comment]
@flodebarre, this is added now.

The 5' and 3' UTRs are sometimes poorly sequenced, so I added options to the gene dropdown for both *full genome* and *full genome except the UTRs*.
